pretzel: 
    engine: razor

category_pages_layout: category
tag_pages_layout: tag

# Site settings
author: bsatroop53.com
title: BSA Troop 53 Of Castleton, NY
description: "BSA Troop 53 of Castleton's Website"
url: https://bsatroop53.com
urlnohttp: bsatroop53.com
contact: admin@bsatroop53.com

github: https://github.com/xforever1313/bsatroop53.com
githubissues: https://github.com/xforever1313/bsatroop53.com/issues

exclude:
 - .gitignore
 - .git
 - .gitmodules
 - .tgitconfig
 - .vs
 - .vscode
 - .cake
 - build.cake
 - tools
 - README.md
 - _thumbnails
 - _pretzel
 - _gallerydata
